### ISSUE TITLE
notty-encoding fails to build on OSX 10.11.6

### ISSUE THREAD

**Issue by michael-grunder** [withoutboats/notty#63]
Hi,

I'm trying to compile notty and have run into an error building the encoding package.  Here is the output from my build:

```bash
➜  notty git:(master) cargo build --verbose
       Fresh uuid v0.3.1
       Fresh base64 v0.1.1
       Fresh num-traits v0.1.37
       Fresh unicode-width v0.1.4
       Fresh log v0.3.7
   Compiling notty-encoding v0.1.0 (https://github.com/withoutboats/notty-encoding#ba5daba3)
       Fresh num-integer v0.1.34
     Running `rustc --crate-name notty_encoding /Users/mgrunder/.cargo/git/checkouts/notty-encoding-26bc718f9ba2caca/ba5daba/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=46ffb3a5a218e748 -C extra-filename=-46ffb3a5a218e748 --out-dir /Users/mgrunder/dev/rust-foss-projects/notty/scaffolding/target/debug/deps -L dependency=/Users/mgrunder/dev/rust-foss-projects/notty/scaffolding/target/debug/deps --extern base64=/Users/mgrunder/dev/rust-foss-projects/notty/scaffolding/target/debug/deps/libbase64-21fea01bef6f0feb.rlib --cap-lints allow`
       Fresh num-iter v0.1.33
       Fresh num v0.1.37
       Fresh serde v0.6.15
       Fresh mime v0.1.3
error[E0038]: the trait `cmds::EscCode` cannot be made into an object
 --> /Users/mgrunder/.cargo/git/checkouts/notty-encoding-26bc718f9ba2caca/ba5daba/src/client.rs:6:5
  |
6 |     fn write(&mut self, &EscCode) -> io::Result<()>;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `cmds::EscCode` cannot be made into an object
  |
  = note: the trait cannot contain associated consts like `OPCODE`

error[E0038]: the trait `cmds::EscCode` cannot be made into an object
  --> /Users/mgrunder/.cargo/git/checkouts/notty-encoding-26bc718f9ba2caca/ba5daba/src/client.rs:12:5
   |
12 |     fn write(&mut self, code: &EscCode) -> io::Result<()> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `cmds::EscCode` cannot be made into an object
   |
   = note: the trait cannot contain associated consts like `OPCODE`

error: aborting due to 2 previous errors

error: Could not compile `notty-encoding`.

Caused by:
  process didn't exit successfully: `rustc --crate-name notty_encoding /Users/mgrunder/.cargo/git/checkouts/notty-encoding-26bc718f9ba2caca/ba5daba/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=46ffb3a5a218e748 -C extra-filename=-46ffb3a5a218e748 --out-dir /Users/mgrunder/dev/rust-foss-projects/notty/scaffolding/target/debug/deps -L dependency=/Users/mgrunder/dev/rust-foss-projects/notty/scaffolding/target/debug/deps --extern base64=/Users/mgrunder/dev/rust-foss-projects/notty/scaffolding/target/debug/deps/libbase64-21fea01bef6f0feb.rlib --cap-lints allow` (exit code: 101)
```

rustc:
```zsh
➜  notty git:(master) rustc --version
rustc 1.19.0-nightly (06fb4d256 2017-04-30)
```

OS Information:
```zsh
➜  notty git:(master) system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.11.6 (15G1217)
      Kernel Version: Darwin 15.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: MG-MBP
      User Name: Michael Grunder (mgrunder)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Disabled
      Time since boot: 2 days 13 minutes
```

I was able to find a few places on the net mentioning this error but unfortunately I don't know nearly enough about rust to figure out a solution.  Hopefully I'm not missing something totally obvious here :smiley:

Edit:  I get the same error in Ubuntu.

**Comment by ghost** [comment]
i can second that on debian-stretch
```
> rustup run nightly cargo build
   Compiling notty-encoding v0.1.0 (https://github.com/withoutboats/notty-encoding#ba5daba3)
   Compiling num v0.1.37
   Compiling serde v0.6.15
error[E0038]: the trait `cmds::EscCode` cannot be made into an object
 --> /home/kon/.cargo/git/checkouts/notty-encoding-26bc718f9ba2caca/ba5daba/src/client.rs:6:5
  |
6 |     fn write(&mut self, &EscCode) -> io::Result<()>;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `cmds::EscCode` cannot be made into an object
  |
  = note: the trait cannot contain associated consts like `OPCODE`

error[E0038]: the trait `cmds::EscCode` cannot be made into an object
  --> /home/kon/.cargo/git/checkouts/notty-encoding-26bc718f9ba2caca/ba5daba/src/client.rs:12:5
   |
12 |     fn write(&mut self, code: &EscCode) -> io::Result<()> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `cmds::EscCode` cannot be made into an object
   |
   = note: the trait cannot contain associated consts like `OPCODE`

error: aborting due to 2 previous errors

error: Could not compile `notty-encoding`.
Build failed, waiting for other jobs to finish...
error: build failed

> uname -a
Linux ktsakiltzidis 4.9.0-3-amd64 #1 SMP Debian 4.9.25-1 (2017-05-02) x86_64 GNU/Linux
```

**Comment by ghost** [comment]
@michael-grunder this seems like an upstream nightly feature being under development https://github.com/rust-lang/rust/issues/29646

**Comment by matthewmummert5** [comment]
I also get the same error compiling on Arch linux:

```
[user@ArchSystem notty]$ rustup run nightly cargo build
   Compiling base64 v0.1.1
   Compiling log v0.3.8
   Compiling unicode-width v0.1.4
   Compiling uuid v0.3.1
   Compiling num-traits v0.1.39
   Compiling notty-encoding v0.1.0 (https://github.com/withoutboats/notty-encoding#ba5daba3)
error[E0038]: the trait `cmds::EscCode` cannot be made into an object
 --> /home/user/.cargo/git/checkouts/notty-encoding-26bc718f9ba2caca/ba5daba/src/client.rs:6:5
  |
6 |     fn write(&mut self, &EscCode) -> io::Result<()>;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `cmds::EscCode` cannot be made into an object
  |
  = note: the trait cannot contain associated consts like `OPCODE`

error[E0038]: the trait `cmds::EscCode` cannot be made into an object
  --> /home/user/.cargo/git/checkouts/notty-encoding-26bc718f9ba2caca/ba5daba/src/client.rs:12:5
   |
12 |     fn write(&mut self, code: &EscCode) -> io::Result<()> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `cmds::EscCode` cannot be made into an object
   |
   = note: the trait cannot contain associated consts like `OPCODE`

error: aborting due to previous error(s)

error: Could not compile `notty-encoding`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by mexus** [comment]
so.. could the project be considered as an abandoned one?

**Comment by tbodt** [comment]
I don't wanna believe it 😢

**Comment by tbodt** [comment]
@withoutboats

**Comment by matthewmummert5** [comment]
Yup, I'd say it's abandoned. The last commit to an actual source file was 10 months ago. It also doesn't compile anymore. I guess that's just part of the cost of developing on Rust nightly.

**Comment by tbodt** [comment]
😢
